# This workflow should build the website with Hugo and deploy it on
# GitHub pages. Edit this file as you wish, otherwise just make sure 
# that this folder contains a workflow exists that it is executed 
# upon pushing the source to the default branch.

name: Build and deploy GitHub pages with Hugo

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.89.4'
          extended: true

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./public
